spring:
  reactor:
    context-propagation: AUTO
  application:
    name: checkout-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
      discovery:
        enabled: true
        service-id: config-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

server:
  port: 8080

management:
  zipkin:
    tracing:
      endpoint: http://localhost:4318/v1/traces
      encoding: PROTO3
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: http://localhost:9090/api/v1/otlp/v1/metrics
        step: 2s
  metrics:
    enabled: false
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

logging:
  loki:
    url: http://localhost:3100/loki/api/v1/push
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway:
            handler:
              RoutePredicateHandlerMapping: DEBUG
    io:
      micrometer:
        registry:
          otlp: ERROR

services:
  products-ms:
    url: http://localhost:8081
    user: products
    pass: products
  carts-ms:
    url: http://localhost:8082
    user: carts
    pass: carts
  legacy:
    url: http://localhost:8181
