version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres-service
    restart: always
    environment:
      POSTGRES_USER: checkout 
      POSTGRES_PASSWORD: checkout
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U checkout"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring-cloud-microservice
      
networks:
  spring-cloud-microservice:
    driver: bridge
